// <auto-generated />
namespace MovieRentalMVCApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MyTry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyTry));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251022491_MyTry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
